import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createDemoStore,STORE_KEY} from '../lib/demo-store.mjs';
const seed={items:JSON.parse(fs.readFileSync(new URL('../data/menu.json',import.meta.url))),settings:JSON.parse(fs.readFileSync(new URL('../data/settings.json',import.meta.url))),orders:[]};
function fixture(){const entries=new Map();const storage={getItem:key=>entries.get(key)||null,setItem:(key,value)=>entries.set(key,value)};return {store:createDemoStore(seed,storage),storage};}
const payload=()=>({action:'order',requestId:crypto.randomUUID(),name:'Test guest',mode:'Dine-in',table:'4',items:[{id:'latte',qty:2}],total:1});
test('seed JSON is not modified and orders survive a store reload',()=>{const {store,storage}=fixture();const result=store.perform('customer',payload());assert.equal(result.order.total,36000);assert.equal(seed.orders.length,0);const reloaded=createDemoStore(seed,storage);assert.equal(reloaded.order(result.order.id).total,36000);assert.equal(reloaded.snapshot('customer').orders.length,0);assert.equal(reloaded.snapshot('manager').orders.length,1);});
test('checkout retries do not duplicate orders',()=>{const {store}=fixture(),p=payload();assert.equal(store.perform('customer',p).order.id,store.perform('customer',p).order.id);assert.equal(store.snapshot('admin').orders.length,1);});
test('invalid quantities, table and empty carts are rejected without saving',()=>{const {store}=fixture();for(const p of [{...payload(),table:'0'},{...payload(),items:[]},{...payload(),items:[{id:'latte',qty:-1}]},{...payload(),items:[{id:'latte',qty:1.2}]}])assert.throws(()=>store.perform('customer',p));assert.equal(store.snapshot('admin').orders.length,0);});
test('manager edits persist; sold out menu items cannot be ordered',()=>{const {store,storage}=fixture();store.perform('manager',{action:'item',item:{...seed.items[0],available:false}});assert.equal(createDemoStore(seed,storage).snapshot('customer').items[0].available,false);assert.throws(()=>store.perform('customer',payload()),/unavailable/);});
test('completed orders leave live queue but remain in reports',()=>{const {store}=fixture(),o=store.perform('customer',payload()).order;store.perform('manager',{action:'status',id:o.id,status:'Completed',payment:'Paid'});assert.equal(store.snapshot('manager').orders.length,0);assert.equal(store.snapshot('admin').orders[0].payment,'Paid');});
test('invoices retain original price and settings after edits',()=>{const {store}=fixture();store.perform('admin',{action:'settings',settings:{...seed.settings,taxRate:5}});const o=store.perform('customer',payload()).order;assert.equal(o.tax,1800);store.perform('manager',{action:'item',item:{...seed.items[0],price:999}});store.perform('admin',{action:'settings',settings:{...seed.settings,name:'Changed'}});assert.equal(store.order(o.id).total,37800);assert.equal(store.order(o.id).cafe.name,'Brew & Bloom');assert.equal(store.order(o.id).items[0].price,18000);});
test('JSON backups contain menu, settings and full order history',()=>{const {store}=fixture();store.perform('customer',payload());const backup=JSON.parse(store.exportJSON());assert.equal(backup.version,1);assert.equal(backup.items.length,8);assert.equal(backup.orders.length,1);assert.equal(backup.settings.name,'Brew & Bloom');});
test('corrupt or unavailable browser storage produces a useful error',()=>{const {store,storage}=fixture();storage.setItem(STORE_KEY,'broken');assert.throws(()=>store.snapshot('admin'),/could not be read/);const full=createDemoStore(seed,{getItem:()=>null,setItem:()=>{throw Error('Quota');}});assert.throws(()=>full.perform('customer',payload()),/could not save/);});
test('view action routing stays separate (not a security boundary)',()=>{const {store}=fixture();assert.throws(()=>store.perform('customer',{action:'settings'}));assert.throws(()=>store.perform('manager',{action:'settings'}));assert.throws(()=>store.perform('admin',payload()));});
