import {cafeDb as db,cafeContext as context} from '../../cafe-access';
import {canAccessSurface,canPerform} from '../../access-policy';
import {initialItems,defaultSettings,categories} from '../../data';
export const dynamic='force-dynamic';
async function save(id:string,kind:string,data:unknown){await db().prepare('INSERT INTO records(id,kind,data) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,kind,JSON.stringify(data)).run();}
async function menu(){const r=await db().prepare("SELECT data FROM records WHERE kind='item'").all<{data:string}>();const overrides=new Map(r.results.map(x=>{const i=JSON.parse(x.data);return[i.id,i]}));return [...initialItems.map(i=>overrides.get(i.id)||i),...Array.from(overrides.values()).filter(i=>!initialItems.some(x=>x.id===i.id))];}
const json=(data:unknown,init:ResponseInit={})=>Response.json(data,{...init,headers:{...init.headers,'Cache-Control':'private, no-store','Vary':'Cookie'}});
const fail=(message:string,status=400)=>json({error:message},{status});
export async function GET(req:Request){
 try{
  const c=await context();const url=new URL(req.url);const surface=url.searchParams.get('surface')||'customer';
  if(!canAccessSurface(c.role,surface))return fail('This view is not available to your account',403);
  if(url.searchParams.has('order')){
   const o=await db().prepare('SELECT * FROM orders WHERE id=?').bind(url.searchParams.get('order')).first<any>();
   if(!o||(surface==='customer'&&o.token!==url.searchParams.get('token')))return fail('Order not found',404);
   return json(JSON.parse(o.data));
  }
  const items=surface==='admin'?[]:await menu();let orders:any[]=[];
  if(surface!=='customer'){
   const query=surface==='manager'?"SELECT data FROM orders WHERE json_extract(data,'$.status') NOT IN ('Completed','Cancelled') ORDER BY created DESC LIMIT 1000":'SELECT data FROM orders ORDER BY created DESC LIMIT 1000';
   const r=await db().prepare(query).all<{data:string}>();orders=r.results.map(x=>JSON.parse(x.data));
  }
  const {managerEmail,...publicSettings}=c.s;
  return json({items,settings:surface==='admin'?c.s:publicSettings,role:c.role,orders});
 }catch(e){console.error(e);return fail('We could not load the café. Please try again.',503);}
}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return fail('Invalid request',403);const b=await req.json() as any;const c=await context();const surface=new URL(req.url).searchParams.get('surface')||'customer';if(b.action==='setup'){if(surface!=='admin')return fail('Owner setup is only available in administration',403);if(!c.user)return fail('Sign in to set up your café',401);if(c.owner)return fail('Café already configured',409);await db().prepare("INSERT OR IGNORE INTO records(id,kind,data) VALUES('owner','owner',?)").bind(JSON.stringify({id:c.user.userId})).run();return json({ok:true});}
if(!canAccessSurface(c.role,surface)||!canPerform(c.role,b.action))return fail('This action is not available to your account',403);
if(b.action==='order'){if(!Array.isArray(b.items)||!b.items.length||b.items.length>40)return fail('Your basket is empty or too large');if(!['Dine-in','Takeaway'].includes(b.mode)||typeof b.name!=='string'||!b.name.trim()||b.name.length>80)return fail('Please enter your name and order type');if(b.mode==='Dine-in'&&!/^\d{1,3}$/.test(b.table))return fail('Enter a table number from 1 to 999');if(typeof b.requestId!=='string'||!/^[a-zA-Z0-9-]{20,80}$/.test(b.requestId))return fail('Invalid order request');const existing=await db().prepare('SELECT data,token FROM orders WHERE request_id=?').bind(b.requestId).first<any>();if(existing)return json({order:JSON.parse(existing.data),token:existing.token});const all=await menu();const lines=[];for(const line of b.items){const item=all.find(i=>i.id===line.id);if(!item?.available||!Number.isInteger(line.qty)||line.qty<1||line.qty>20)return fail('An item is unavailable or quantity is invalid');lines.push({id:item.id,name:item.name,price:Math.round(item.price*100),qty:line.qty});}const subtotal=lines.reduce((s,i)=>s+i.price*i.qty,0);const tax=Math.round(subtotal*c.s.taxRate/100);const id=crypto.randomUUID();const token=crypto.randomUUID();const order={id,number:id.slice(0,6).toUpperCase(),created:Date.now(),name:b.name.trim(),mode:b.mode,table:b.mode==='Dine-in'?b.table:'',notes:String(b.notes||'').slice(0,500),items:lines,subtotal,tax,taxRate:c.s.taxRate,total:subtotal+tax,status:'Received',payment:'Unpaid',cafe:{name:c.s.name,address:c.s.address,upi:c.s.upi}};await db().prepare('INSERT INTO orders(id,token,request_id,created,data) VALUES(?,?,?,?,?)').bind(id,token,b.requestId,order.created,JSON.stringify(order)).run();return json({order,token});}
if(c.role==='customer')return fail('Staff access required',403);
if(b.action==='item'){const i=b.item;if(!i||typeof i.name!=='string'||!i.name.trim()||i.name.length>80||typeof i.description!=='string'||i.description.length>300||!Number.isFinite(i.price)||i.price<=0||i.price>100000||!categories.includes(i.category)||i.category==='All items')return fail('Check item name, category and price');if(i.image&&!/^https:\/\//.test(i.image))return fail('Use an HTTPS image URL');const item={id:i.id||crypto.randomUUID(),name:i.name.trim(),description:i.description,price:Math.round(i.price*100)/100,category:i.category,veg:!!i.veg,available:!!i.available,image:String(i.image||'').slice(0,2000),tag:String(i.tag||'').slice(0,30)};await save('item:'+item.id,'item',item);return json({ok:true});}
if(b.action==='status'){const row=await db().prepare('SELECT data FROM orders WHERE id=?').bind(b.id).first<any>();if(!row)return fail('Order not found',404);const o=JSON.parse(row.data);if(b.status){if(!['Received','Preparing','Ready','Completed','Cancelled'].includes(b.status))return fail('Invalid status');o.status=b.status;}if(b.payment){if(!['Unpaid','Paid'].includes(b.payment))return fail('Invalid payment');o.payment=b.payment;}await db().prepare('UPDATE orders SET data=? WHERE id=?').bind(JSON.stringify(o),b.id).run();return json({ok:true});}
if(b.action==='settings'){if(c.role!=='admin')return fail('Admin access required',403);const s=b.settings;if(!s.name?.trim()||s.name.length>80||s.upi&&!/^[\w.\-]{2,}@[\w.\-]{2,}$/.test(s.upi)||!Number.isFinite(s.taxRate)||s.taxRate<0||s.taxRate>30)return fail('Check café name, UPI ID and tax rate');await save('settings','settings',{name:s.name.trim(),address:String(s.address||'').slice(0,300),upi:s.upi||'',managerEmail:String(s.managerEmail||'').trim().toLowerCase(),taxRate:s.taxRate});return json({ok:true});}return fail('Unknown action');}catch(e){console.error(e);return fail('Could not save. Please try again.',503);}}
